### ISSUE TITLE
Realism craft, Pferde reiten ist nicht möglich..

### ISSUE THREAD

**Issue by FreyJeyzZ** [slimeixd1/RealismCraft#2]
Hallo, man kann leider zurzeit nicht mit Pferden reiten. Aufsetzen kann man nur ist keine Steuerung möglich... könnt ihr mir mal helfen?
LG FreyJeyzZ

**Comment by slimeixd1** [comment]
Klar, ich werde es mir ansehen

**Comment by FreyJeyzZ** [comment]
Hallo, ich wollte mich nochmal bedanken.
Es funktioniert wieder alles :D.
LG FreyJeyzZ
